"use client";

import { useEffect, useMemo, useState } from "react";
import { api } from "@/lib/api";
import { useToast } from "@/components/ui/toast";
import { DataTable } from "@/components/ui/data-table";
import { Pill } from "@/components/ui/pill";
import { Card } from "@/components/ui/card";
import { Icon } from "@/components/icons";
import { cn } from "@/lib/utils";
import type { ColumnDef } from "@tanstack/react-table";
import type { Invoice } from "@/lib/types";

const STATUS_FILTERS = ["All", "Paid", "Pending", "Waived"] as const;
type StatusFilter = (typeof STATUS_FILTERS)[number];

export function Billing() {
  const toast = useToast();
  const [invoices, setInvoices] = useState<Invoice[] | null>(null);
  const [filter, setFilter] = useState<StatusFilter>("All");

  useEffect(() => {
    let active = true;
    api
      .get<Invoice[]>("/invoices")
      .then((data) => active && setInvoices(data))
      .catch(() => active && setInvoices([]));
    return () => {
      active = false;
    };
  }, []);

  const download = (inv: Invoice) => {
    const lines = [
      "PRESTIGE SUPPORT SUITE — INVOICE",
      "==================================",
      `Invoice   : ${inv.id}`,
      `Period    : ${inv.period}`,
      `Amount    : ${inv.amount}`,
      `Status    : ${inv.status}`,
      `Method    : ${inv.method}`,
      "",
      "This is a mock invoice generated by the demo billing engine.",
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `invoice-${inv.id}.txt`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
    toast(`${inv.id} downloaded`);
  };

  const list = (invoices ?? []).filter(
    (inv) => filter === "All" || inv.status === filter.toLowerCase(),
  );
  const paid = (invoices ?? []).filter((i) => i.status === "paid");
  const next = invoices?.[0];

  return (
    <div className="flex flex-col gap-6">
      <header>
        <h1 className="text-h1 text-text">Billing</h1>
      </header>

      <div className="grid grid-cols-[repeat(auto-fit,minmax(190px,1fr))] gap-4">
        <Kpi icon="check" label="Paid this cycle" value={String(paid.length)} note="all settled" />
        <Kpi
          icon="card"
          label="Outstanding"
          value={(invoices ?? []).filter((i) => i.status !== "paid" && i.status !== "waived").length > 0 ? "1" : "0"}
          note="0 overdue"
          good
        />
        <Kpi icon="clock" label="Next billing" value={next?.period.split(" – ")[1] ?? "—"} note={next?.method ?? "Visa ···· 4821"} />
      </div>

      <Card title="Invoice register" icon="file">
        <p className="mb-4 text-meta text-text-3">
          Generated on plan change and each billing cycle
        </p>
        <div className="sec-filter mb-4 flex flex-wrap gap-2">
          {STATUS_FILTERS.map((f) => (
            <button
              key={f}
              type="button"
              onClick={() => setFilter(f)}
              className={cn(
                "rounded-sm border px-3 py-1.5 text-[12px] font-semibold transition-colors duration-150",
                filter === f
                  ? "border-primary-border bg-primary-soft text-primary-dark"
                  : "border-border bg-surface text-text-2 hover:bg-surface-2 hover:text-text",
              )}
            >
              {f}
            </button>
          ))}
        </div>
        <div className="w-full">
          {!invoices ? (
            <div className="p-6">
              <div className="skeleton h-10 w-full" />
              <div className="skeleton mt-3 h-10 w-full" />
            </div>
          ) : list.length === 0 ? (
            <p className="px-6 py-12 text-center text-[13px] text-text-3">
              No invoices match “{filter}”.
            </p>
          ) : (
            <InvoiceTable invoices={list} onDownload={download} />
          )}
        </div>
      </Card>
    </div>
  );
}

function InvoiceTable({ invoices, onDownload }: { invoices: Invoice[]; onDownload: (inv: Invoice) => void }) {
  const columns = useMemo<ColumnDef<Invoice, unknown>[]>(
    () => [
      {
        accessorKey: "id",
        header: "Invoice",
        cell: ({ row }) => (
          <span className="font-mono text-code font-semibold text-text">{row.original.id}</span>
        ),
      },
      {
        accessorKey: "period",
        header: "Period",
        cell: ({ row }) => <span className="text-text-2">{row.original.period}</span>,
      },
      {
        accessorKey: "amount",
        header: "Amount",
        cell: ({ row }) => (
          <span className="font-mono text-code tabular-nums">{row.original.amount}</span>
        ),
      },
      {
        accessorKey: "status",
        header: "Status",
        enableSorting: false,
        cell: ({ row }) => <Pill status={row.original.status} />,
      },
      {
        accessorKey: "method",
        header: "Method",
        cell: ({ row }) => <span className="text-text-2">{row.original.method}</span>,
      },
      {
        id: "row_actions",
        header: "",
        enableSorting: false,
        cell: ({ row }) => (
          <div className="text-right">
            <button
              type="button"
              onClick={() => onDownload(row.original)}
              className="inline-flex items-center gap-1 rounded-sm border border-border bg-surface px-2.5 py-1.5 text-[11.5px] font-semibold text-text-2 transition-colors duration-150 hover:bg-surface-3 hover:text-text"
            >
              <Icon name="file" size={13} />
              Download
            </button>
          </div>
        ),
      },
    ],
    [onDownload],
  );
  return <DataTable columns={columns} data={invoices} getRowId={(inv) => inv.id} hoverable borderless />;
}

function Kpi({
  icon,
  label,
  value,
  note,
  good,
}: {
  icon: "check" | "card" | "clock";
  label: string;
  value: string;
  note: string;
  good?: boolean;
}) {
  return (
    <div className="rounded-md border border-border bg-surface p-4 shadow-card">
      <p className="flex items-center justify-between text-[12px] font-semibold text-text-2">
        {label}
        <Icon name={icon} size={14} className={good ? "text-primary" : "text-text-3"} />
      </p>
      <p className="mt-2 text-kpi tabular-nums text-text">{value}</p>
      <p className="mt-1 text-meta text-text-3">{note}</p>
    </div>
  );
}
