export interface EmojiEntry {
  /** Native emoji character (base form; skin tone applied on top). */
  char: string;
  /** CLDR name — used for search and the hover preview line. */
  name: string;
  /** Extra search terms (aliases/keywords). */
  keywords: string[];
  /** Category key — groups the grid and drives the tab nav. */
  category: EmojiCategory;
  /** True when the emoji accepts a Fitzpatrick skin-tone modifier. */
  skinTones?: boolean;
}

export type EmojiCategory =
  | "smileys"
  | "people"
  | "nature"
  | "food"
  | "activity"
  | "travel"
  | "objects"
  | "symbols"
  | "flags";

export const EMOJI_CATEGORIES: { key: EmojiCategory; label: string }[] = [
  { key: "smileys", label: "Smileys" },
  { key: "people", label: "People" },
  { key: "nature", label: "Nature" },
  { key: "food", label: "Food" },
  { key: "activity", label: "Activity" },
  { key: "travel", label: "Travel" },
  { key: "objects", label: "Objects" },
  { key: "symbols", label: "Symbols" },
  { key: "flags", label: "Flags" },
];

export const SKIN_TONES = [
  { tone: "", label: "Default", swatch: "🖐️" },
  { tone: "🏻", label: "Light", swatch: "🖐🏻" },
  { tone: "🏼", label: "Medium-light", swatch: "🖐🏼" },
  { tone: "🏽", label: "Medium", swatch: "🖐🏽" },
  { tone: "🏾", label: "Medium-dark", swatch: "🖐🏾" },
  { tone: "🏿", label: "Dark", swatch: "🖐🏿" },
] as const;

const E = (
  char: string,
  name: string,
  category: EmojiCategory,
  keywords: string[],
  skinTones = false,
): EmojiEntry => ({ char, name, category, keywords, skinTones });

/** Curated emoji dataset (no external dep) — every category, CLDR names for
 *  search + preview, and skin-tone flags on hand emoji/people. */
export const EMOJIS: EmojiEntry[] = [
  // Smileys & emotion
  E("😀", "Grinning face", "smileys", ["grin", "happy", "smile", "joy"]),
  E("😃", "Grinning face with big eyes", "smileys", ["happy", "joy", "haha", "smile"]),
  E("😄", "Grinning face with smiling eyes", "smileys", ["happy", "joy", "laugh"]),
  E("😁", "Beaming face with smiling eyes", "smileys", ["happy", "laugh", "smile"]),
  E("😆", "Grinning squinting face", "smileys", ["laugh", "happy", "haha"]),
  E("😅", "Grinning face with sweat", "smileys", ["nervous", "awkward", "laugh"]),
  E("😂", "Face with tears of joy", "smileys", ["laugh", "cry", "tears", "funny"]),
  E("🤣", "Rolling on the floor laughing", "smileys", ["lol", "funny", "laugh"]),
  E("🙂", "Slightly smiling face", "smileys", ["smile", "ok"]),
  E("🙃", "Upside-down face", "smileys", ["silly", "ironic", "sarcastic"]),
  E("😉", "Winking face", "smileys", ["wink", "flirt", "joke"]),
  E("😊", "Smiling face with smiling eyes", "smileys", ["happy", "kind", "blush"]),
  E("😇", "Smiling face with halo", "smileys", ["innocent", "angel", "good"]),
  E("🥰", "Smiling face with hearts", "smileys", ["love", "affection", "adore"]),
  E("😍", "Smiling face with heart-eyes", "smileys", ["love", "crush", "heart"]),
  E("🤩", "Star-struck", "smileys", ["excited", "wow", "amazed"]),
  E("😘", "Face blowing a kiss", "smileys", ["kiss", "love", "smooch"]),
  E("😗", "Kissing face", "smileys", ["kiss", "blow"]),
  E("😚", "Kissing face with closed eyes", "smileys", ["kiss", "love"]),
  E("😋", "Face savoring food", "smileys", ["yum", "delicious", "tasty"]),
  E("😛", "Face with tongue", "smileys", ["playful", "tongue"]),
  E("😜", "Winking face with tongue", "smileys", ["joke", "playful", "silly"]),
  E("🤪", "Zany face", "smileys", ["silly", "crazy", "fun"]),
  E("😝", "Squinting face with tongue", "smileys", ["playful", "fun"]),
  E("🤑", "Money-mouth face", "smileys", ["money", "rich", "greedy"]),
  E("🤗", "Smiling face with open hands", "smileys", ["hug", "hello", "thanks"]),
  E("🤭", "Face with hand over mouth", "smileys", ["oops", "shh", "secret"]),
  E("🫢", "Face with open eyes and hand over mouth", "smileys", ["surprised", "shocked", "oops"]),
  E("🤫", "Shushing face", "smileys", ["quiet", "shh", "silence"]),
  E("🤔", "Thinking face", "smileys", ["think", "ponder", "consider"]),
  E("🤐", "Zipper-mouth face", "smileys", ["quiet", "sealed", "silence"]),
  E("🤨", "Face with raised eyebrow", "smileys", ["skeptical", "doubt", "sus"]),
  E("😐", "Neutral face", "smileys", ["meh", "neutral", "plain"]),
  E("😑", "Expressionless face", "smileys", ["bored", "blank", "meh"]),
  E("😶", "Face without mouth", "smileys", ["silent", "speechless"]),
  E("😏", "Smirking face", "smileys", ["smug", "sly", "flirt"]),
  E("😒", "Unamused face", "smileys", ["annoyed", "displeased", "meh"]),
  E("🙄", "Face with rolling eyes", "smileys", ["annoyed", "whatever", "eyeroll"]),
  E("😬", "Grimacing face", "smileys", ["awkward", "cringe", "nervous"]),
  E("😮‍💨", "Face exhaling", "smileys", ["relief", "sigh", "tired"]),
  E("🤥", "Lying face", "smileys", ["lie", "pinocchio", "deceit"]),
  E("😪", "Sleepy face", "smileys", ["tired", "sleep", "yawning"]),
  E("😴", "Sleeping face", "smileys", ["sleep", "zzz", "tired"]),
  E("😌", "Relieved face", "smileys", ["relieved", "calm", "peace"]),
  E("😷", "Face with medical mask", "smileys", ["sick", "surgery", "mask"]),
  E("🤒", "Face with thermometer", "smileys", ["sick", "fever", "ill"]),
  E("🤕", "Face with head-bandage", "smileys", ["hurt", "injury", "bandage"]),
  E("🤢", "Nauseated face", "smileys", ["sick", "gross", "vomit"]),
  E("🤮", "Face vomiting", "smileys", ["sick", "vomit", "gross"]),
  E("🤧", "Sneezing face", "smileys", ["sneeze", "cold", "allergy"]),
  E("🥵", "Hot face", "smileys", ["hot", "heat", "sweat"]),
  E("🥶", "Cold face", "smileys", ["cold", "freezing", "ice"]),
  E("🥴", "Woozy face", "smileys", ["drunk", "dizzy", "confused"]),
  E("😵", "Dizzy face", "smileys", ["dizzy", "shocked", "spinning"]),
  E("🤯", "Exploding head", "smileys", ["mind", "blown", "shock"]),
  E("🤠", "Cowboy hat face", "smileys", ["cowboy", "yeehaw", "western"]),
  E("🥳", "Partying face", "smileys", ["party", "celebration", "congrats"]),
  E("🥸", "Disguised face", "smileys", ["disguise", "incognito", "spy"]),
  E("😎", "Smiling face with sunglasses", "smileys", ["cool", "sunglasses", "boss"]),
  E("🤓", "Nerd face", "smileys", ["nerd", "geek", "smart"]),
  E("🧐", "Face with monocle", "smileys", ["inspect", "fancy", "look"]),
  E("😕", "Confused face", "smileys", ["confused", "puzzled", "unsure"]),
  E("😟", "Worried face", "smileys", ["worried", "concern", "upset"]),
  E("🙁", "Slightly frowning face", "smileys", ["sad", "frown", "down"]),
  E("☹️", "Frowning face", "smileys", ["sad", "frown", "unhappy"]),
  E("😮", "Face with open mouth", "smileys", ["surprised", "wow", "shock"]),
  E("😯", "Hushed face", "smileys", ["surprised", "quiet", "shocked"]),
  E("😲", "Astonished face", "smileys", ["shocked", "amazed", "wow"]),
  E("😳", "Flushed face", "smileys", ["embarrassed", "blush", "shy"]),
  E("🥺", "Pleading face", "smileys", ["beg", "please", "puppy eyes"]),
  E("😦", "Frowning face with open mouth", "smileys", ["sad", "worried", "uh oh"]),
  E("😧", "Anguished face", "smileys", ["stressed", "distressed", "upset"]),
  E("😨", "Fearful face", "smileys", ["scared", "afraid", "fear"]),
  E("😰", "Anxious face with sweat", "smileys", ["nervous", "anxious", "sweat"]),
  E("😥", "Sad but relieved face", "smileys", ["relieved", "whew", "phew"]),
  E("😢", "Crying face", "smileys", ["cry", "sad", "tear"]),
  E("😭", "Loudly crying face", "smileys", ["cry", "sobbing", "tears"]),
  E("😱", "Face screaming in fear", "smileys", ["scream", "shock", "fear"]),
  E("😖", "Confounded face", "smileys", ["frustrated", "confused", "upset"]),
  E("😣", "Persevering face", "smileys", ["struggling", "persevere", "grr"]),
  E("😞", "Disappointed face", "smileys", ["sad", "disappointed", "down"]),
  E("😓", "Downcast face with sweat", "smileys", ["sweat", "stressed", "sad"]),
  E("😩", "Weary face", "smileys", ["tired", "exhausted", "worn"]),
  E("😫", "Tired face", "smileys", ["exhausted", "tired", "frustrated"]),
  E("🥱", "Yawning face", "smileys", ["yawn", "tired", "bored"]),
  E("😤", "Face with steam from nose", "smileys", ["angry", "frustrated", "steam"]),
  E("😡", "Pouting face", "smileys", ["angry", "mad", "pout"]),
  E("😠", "Angry face", "smileys", ["angry", "mad", "furious"]),
  E("🤬", "Face with symbols on mouth", "smileys", ["angry", "cursing", "swear"]),
  E("😈", "Smiling face with horns", "smileys", ["devil", "mischief", "evil"]),
  E("👿", "Angry face with horns", "smileys", ["devil", "evil", "angry"]),
  E("💀", "Skull", "smileys", ["death", "dead", "skull"]),
  E("👻", "Ghost", "smileys", ["halloween", "spooky", "boo"]),
  E("👽", "Alien", "smileys", ["ufo", "space", "extraterrestrial"]),
  E("🤖", "Robot", "smileys", ["ai", "bot", "machine"]),
  E("💩", "Pile of poo", "smileys", ["poop", "poo", "crap"]),
  E("😺", "Grinning cat", "smileys", ["cat", "happy", "grin"]),
  E("😸", "Grinning cat with smiling eyes", "smileys", ["cat", "happy"]),
  E("😻", "Smiling cat with heart-eyes", "smileys", ["cat", "love"]),
  E("🙀", "Weary cat", "smileys", ["cat", "shock", "surprised"]),
  E("😿", "Crying cat", "smileys", ["cat", "sad", "cry"]),
  E("💋", "Kiss mark", "smileys", ["kiss", "love", "lips"]),
  E("💘", "Heart with arrow", "smileys", ["love", "cupid", "crush"]),
  E("💝", "Heart with ribbon", "smileys", ["love", "gift", "valentine"]),
  E("💖", "Sparkling heart", "smileys", ["love", "sparkle"]),
  E("💗", "Growing heart", "smileys", ["love", "growing", "beat"]),
  E("💓", "Beating heart", "smileys", ["love", "heartbeat", "pulse"]),
  E("💞", "Revolving hearts", "smileys", ["love", "revolving"]),
  E("💕", "Two hearts", "smileys", ["love", "hearts", "affection"]),
  E("💌", "Love letter", "smileys", ["love", "letter", "mail"]),
  E("💔", "Broken heart", "smileys", ["heartbreak", "sad", "breakup"]),
  E("❤️", "Red heart", "smileys", ["love", "heart", "red"]),
  E("🩷", "Pink heart", "smileys", ["love", "pink", "heart"]),
  E("🧡", "Orange heart", "smileys", ["love", "orange", "heart"]),
  E("💛", "Yellow heart", "smileys", ["love", "yellow", "heart"]),
  E("💚", "Green heart", "smileys", ["love", "green", "heart"]),
  E("💙", "Blue heart", "smileys", ["love", "blue", "heart"]),
  E("🩵", "Light blue heart", "smileys", ["love", "light blue", "heart"]),
  E("💜", "Purple heart", "smileys", ["love", "purple", "heart"]),
  E("🖤", "Black heart", "smileys", ["love", "black", "heart"]),
  E("🤍", "White heart", "smileys", ["love", "white", "heart"]),
  E("💯", "Hundred points", "smileys", ["100", "perfect", "score"]),
  E("💢", "Anger symbol", "smileys", ["angry", "mad", "vein"]),
  E("💥", "Collision", "smileys", ["boom", "explosion", "impact"]),
  E("💫", "Dizzy", "smileys", ["dizzy", "sparkle", "star"]),
  E("💦", "Sweat droplets", "smileys", ["sweat", "water", "drops"]),
  E("💨", "Dashing away", "smileys", ["wind", "speed", "dash"]),
  E("🕳️", "Hole", "smileys", ["hole", "dig"]),
  E("💬", "Speech balloon", "smileys", ["chat", "speech", "bubble", "talk"]),
  E("💭", "Thought balloon", "smileys", ["thought", "think", "bubble"]),
  E("💤", "Zzz", "smileys", ["sleep", "tired", "zzz"]),
  E("✨", "Sparkles", "smileys", ["sparkle", "shiny", "glitter", "magic"]),
  E("🌟", "Glowing star", "smileys", ["star", "glow", "shine"]),
  E("⭐", "Star", "smileys", ["star", "rating"]),
  E("🔥", "Fire", "smileys", ["hot", "flame", "lit", "burn"]),
  E("🎉", "Party popper", "smileys", ["party", "congrats", "celebration", "tada"]),

  // People & body
  E("👋", "Waving hand", "people", ["wave", "hello", "bye", "hi"], true),
  E("🤚", "Raised back of hand", "people", ["hand", "stop", "raised"], true),
  E("🖐️", "Hand with fingers splayed", "people", ["hand", "splayed", "five"], true),
  E("✋", "Raised hand", "people", ["hand", "high five", "stop"], true),
  E("🖖", "Vulcan salute", "people", ["vulcan", "spock", "live long"], true),
  E("👌", "OK hand", "people", ["ok", "perfect", "fine"], true),
  E("🤌", "Pinched fingers", "people", ["chef", "italian", "pinch"], true),
  E("🤏", "Pinching hand", "people", ["pinch", "small", "tiny"], true),
  E("✌️", "Victory hand", "people", ["peace", "victory", "two"], true),
  E("🤞", "Crossed fingers", "people", ["luck", "fingers crossed", "hope"], true),
  E("🤟", "Love-you gesture", "people", ["love", "ily", "gesture"], true),
  E("🤘", "Sign of the horns", "people", ["rock", "horns", "metal"], true),
  E("🤙", "Call me hand", "people", ["call", "hang loose", "phone"], true),
  E("👈", "Backhand index pointing left", "people", ["point", "left"], true),
  E("👉", "Backhand index pointing right", "people", ["point", "right"], true),
  E("👆", "Backhand index pointing up", "people", ["point", "up"], true),
  E("🖕", "Middle finger", "people", ["flip", "middle finger"], true),
  E("👇", "Backhand index pointing down", "people", ["point", "down"], true),
  E("☝️", "Index pointing up", "people", ["point", "up"], true),
  E("👍", "Thumbs up", "people", ["like", "good", "approve", "yes"], true),
  E("👎", "Thumbs down", "people", ["dislike", "bad", "no"], true),
  E("✊", "Raised fist", "people", ["fist", "power", "solidarity"], true),
  E("👊", "Oncoming fist", "people", ["fist", "bump", "punch"], true),
  E("🤛", "Left-facing fist", "people", ["fist", "bump", "pound"], true),
  E("🤜", "Right-facing fist", "people", ["fist", "bump", "pound"], true),
  E("👏", "Clapping hands", "people", ["applause", "clap", "well done"], true),
  E("🙌", "Raising hands", "people", ["praise", "hallelujah", "celebrate"], true),
  E("🫶", "Heart hands", "people", ["love", "heart", "hug"], true),
  E("🤝", "Handshake", "people", ["deal", "agreement", "hello"], true),
  E("🙏", "Folded hands", "people", ["please", "thanks", "pray"], true),
  E("💪", "Flexed biceps", "people", ["strength", "muscle", "workout", "strong"], true),
  E("🦾", "Mechanical arm", "people", ["robot", "prosthetic", "arm"]),
  E("👂", "Ear", "people", ["ear", "listen", "hear"], true),
  E("👃", "Nose", "people", ["nose", "smell"], true),
  E("👀", "Eyes", "people", ["eyes", "look", "see"]),
  E("👁️", "Eye", "people", ["eye", "look", "see"]),
  E("👅", "Tongue", "people", ["tongue", "taste", "lick"]),
  E("👄", "Mouth", "people", ["mouth", "lips", "kiss"]),
  E("👶", "Baby", "people", ["baby", "child", "newborn"]),
  E("🧒", "Child", "people", ["child", "kid"]),
  E("👦", "Boy", "people", ["boy", "child", "kid"]),
  E("👧", "Girl", "people", ["girl", "child", "kid"]),
  E("🧑", "Person", "people", ["person", "adult"]),
  E("👨", "Man", "people", ["man", "adult", "male"]),
  E("👩", "Woman", "people", ["woman", "adult", "female"]),
  E("🧑‍🦳", "Person with white hair", "people", ["person", "older", "white hair"]),
  E("👴", "Old man", "people", ["man", "grandpa", "elderly"]),
  E("👵", "Old woman", "people", ["woman", "grandma", "elderly"]),
  E("👮", "Police officer", "people", ["police", "cop", "law"], true),
  E("🕵️", "Detective", "people", ["detective", "spy", "sleuth"], true),
  E("💂", "Guard", "people", ["guard", "beefeater", "royal"], true),
  E("👷", "Construction worker", "people", ["worker", "builder", "hard hat"], true),
  E("🤴", "Prince", "people", ["prince", "royal", "crown"]),
  E("👸", "Princess", "people", ["princess", "royal", "crown"]),
  E("👳", "Person wearing turban", "people", ["turban", "headwear"], true),
  E("👲", "Person with skullcap", "people", ["skullcap", "chinese", "cap"]),
  E("🧕", "Woman with headscarf", "people", ["headscarf", "hijab"]),
  E("🤵", "Person in tuxedo", "people", ["tuxedo", "groom", "formal"]),
  E("👰", "Person with veil", "people", ["bride", "veil", "wedding"]),
  E("🤰", "Pregnant woman", "people", ["pregnant", "baby", "expecting"]),
  E("🤱", "Breastfeeding", "people", ["breastfeed", "nursing", "baby"]),
  E("👼", "Baby angel", "people", ["angel", "cherub", "baby"]),
  E("🎅", "Santa Claus", "people", ["santa", "christmas", "ho ho ho"]),
  E("🤶", "Mrs. Claus", "people", ["mrs claus", "christmas", "santa"]),
  E("🦸", "Superhero", "people", ["hero", "superman", "power"]),
  E("🦹", "Supervillain", "people", ["villain", "evil", "bad"]),
  E("🧙", "Mage", "people", ["wizard", "magic", "sorcerer"]),
  E("🧚", "Fairy", "people", ["fairy", "magic", "wings"]),
  E("🧛", "Vampire", "people", ["vampire", "fang", "blood"]),
  E("🧜", "Mermaid", "people", ["mermaid", "merman", "sea"]),
  E("🧝", "Elf", "people", ["elf", "fantasy", "ears"]),
  E("🧞", "Genie", "people", ["genie", "wish", "lamp"]),
  E("🧟", "Zombie", "people", ["zombie", "undead", "walker"]),
  E("💆", "Person getting massage", "people", ["massage", "spa", "relax"], true),
  E("💇", "Person getting haircut", "people", ["haircut", "barber", "salon"], true),
  E("🚶", "Person walking", "people", ["walk", "stroll", "pedestrian"], true),
  E("🧍", "Person standing", "people", ["stand", "standing"]),
  E("🧎", "Person kneeling", "people", ["kneel", "pray", "thanks"]),
  E("🏃", "Person running", "people", ["run", "sprint", "jog"], true),
  E("💃", "Woman dancing", "people", ["dance", "dancer", "party"]),
  E("🕺", "Man dancing", "people", ["dance", "dancer", "party"]),
  E("🕴️", "Person in suit levitating", "people", ["levitate", "suit", "hover"]),
  E("🧖", "Person in steamy room", "people", ["sauna", "steam", "spa"]),
  E("🧗", "Person climbing", "people", ["climb", "rock climbing", "mountaineer"]),
  E("🤺", "Person fencing", "people", ["fence", "fencing", "sword"]),
  E("🏇", "Horse racing", "people", ["horse", "race", "jockey"]),
  E("⛷️", "Skier", "people", ["ski", "skiing", "snow"]),
  E("🏂", "Snowboarder", "people", ["snowboard", "snow"]),
  E("🏌️", "Person golfing", "people", ["golf", "golfer", "swing"]),
  E("🏄", "Person surfing", "people", ["surf", "surfing", "wave"]),
  E("🚣", "Person rowing boat", "people", ["row", "rowing", "boat"]),
  E("🏊", "Person swimming", "people", ["swim", "swimming", "pool"]),
  E("🏋️", "Person lifting weights", "people", ["gym", "lift", "weight"]),
  E("🚴", "Person biking", "people", ["bike", "cycle", "cycling"]),
  E("🚵", "Person mountain biking", "people", ["mtb", "bike", "cycling"]),
  E("🤸", "Person cartwheeling", "people", ["cartwheel", "gymnastics", "flip"]),
  E("🤼", "People wrestling", "people", ["wrestle", "wrestling", "fight"]),
  E("🤽", "Person playing water polo", "people", ["water polo", "sport"]),
  E("🤾", "Person playing handball", "people", ["handball", "sport"]),
  E("🤹", "Person juggling", "people", ["juggle", "juggling", "multi-task"]),
  E("🧘", "Person in lotus position", "people", ["yoga", "meditate", "lotus"]),
  E("🛀", "Person taking bath", "people", ["bath", "bathtub", "soak"]),
  E("🛌", "Person in bed", "people", ["bed", "sleep", "rest"]),
  E("👭", "Women holding hands", "people", ["friends", "couple", "hand in hand"]),
  E("👫", "Woman and man holding hands", "people", ["couple", "date", "holding hands"]),
  E("👬", "Men holding hands", "people", ["friends", "couple", "hand in hand"]),
  E("💏", "Kiss", "people", ["kiss", "couple", "love"]),
  E("💑", "Couple with heart", "people", ["couple", "love", "relationship"]),
  E("👪", "Family", "people", ["family", "parents", "children"]),
  E("🗣️", "Speaking head", "people", ["speak", "speaking", "talk"]),
  E("👤", "Bust in silhouette", "people", ["user", "profile", "silhouette"]),
  E("👥", "Busts in silhouette", "people", ["users", "group", "people"]),
  E("🧓", "Older person", "people", ["older", "senior", "elderly"]),
  E("🧑‍🤝‍🧑", "People holding hands", "people", ["holding hands", "together", "friends"]),
  E("🧔", "Bearded person", "people", ["beard", "man", "bearded"]),

  // Animals & nature
  E("🐶", "Dog face", "nature", ["dog", "puppy", "pet"]),
  E("🐱", "Cat face", "nature", ["cat", "kitten", "pet"]),
  E("🐭", "Mouse face", "nature", ["mouse", "rat"]),
  E("🐹", "Hamster", "nature", ["hamster", "pet"]),
  E("🐰", "Rabbit face", "nature", ["rabbit", "bunny"]),
  E("🦊", "Fox", "nature", ["fox", "foxy"]),
  E("🐻", "Bear", "nature", ["bear", "teddy"]),
  E("🐼", "Panda", "nature", ["panda", "bear"]),
  E("🐨", "Koala", "nature", ["koala", "bear"]),
  E("🐯", "Tiger face", "nature", ["tiger", "cat"]),
  E("🦁", "Lion", "nature", ["lion", "king", "roar"]),
  E("🐮", "Cow face", "nature", ["cow", "moo"]),
  E("🐷", "Pig face", "nature", ["pig", "oink"]),
  E("🐸", "Frog", "nature", ["frog", "ribbit"]),
  E("🐵", "Monkey face", "nature", ["monkey", "ape"]),
  E("🙈", "See-no-evil monkey", "nature", ["monkey", "blind", "hide"]),
  E("🙉", "Hear-no-evil monkey", "nature", ["monkey", "deaf", "hide"]),
  E("🙊", "Speak-no-evil monkey", "nature", ["monkey", "mute", "hide"]),
  E("🐔", "Chicken", "nature", ["chicken", "hen", "cluck"]),
  E("🐧", "Penguin", "nature", ["penguin", "antarctic"]),
  E("🐦", "Bird", "nature", ["bird", "tweet"]),
  E("🐤", "Baby chick", "nature", ["chick", "baby", "bird"]),
  E("🦄", "Unicorn", "nature", ["unicorn", "magic", "mythical"]),
  E("🐝", "Honeybee", "nature", ["bee", "honey", "buzz"]),
  E("🦋", "Butterfly", "nature", ["butterfly", "insect", "pretty"]),
  E("🐌", "Snail", "nature", ["snail", "slow"]),
  E("🐞", "Lady beetle", "nature", ["ladybug", "beetle", "insect"]),
  E("🐢", "Turtle", "nature", ["turtle", "tortoise", "slow"]),
  E("🐠", "Tropical fish", "nature", ["fish", "tropical"]),
  E("🐬", "Dolphin", "nature", ["dolphin", "sea", "ocean"]),
  E("🐳", "Spouting whale", "nature", ["whale", "ocean", "sea"]),
  E("🐊", "Crocodile", "nature", ["crocodile", "alligator"]),
  E("🦈", "Shark", "nature", ["shark", "ocean", "fish"]),
  E("🦖", "T-Rex", "nature", ["dinosaur", "trex", "rex"]),
  E("🦕", "Sauropod", "nature", ["dinosaur", "long neck"]),
  E("🌸", "Cherry blossom", "nature", ["flower", "blossom", "spring"]),
  E("💐", "Bouquet", "nature", ["flowers", "bouquet", "gift"]),
  E("🌹", "Rose", "nature", ["flower", "rose", "love"]),
  E("🥀", "Wilted flower", "nature", ["flower", "wilted", "sad"]),
  E("🌺", "Hibiscus", "nature", ["flower", "hibiscus"]),
  E("🌻", "Sunflower", "nature", ["flower", "sunflower", "sun"]),
  E("🌷", "Tulip", "nature", ["flower", "tulip", "spring"]),
  E("🌱", "Seedling", "nature", ["plant", "seedling", "sprout"]),
  E("🌲", "Evergreen tree", "nature", ["tree", "pine", "evergreen"]),
  E("🌳", "Deciduous tree", "nature", ["tree", "oak", "leaf"]),
  E("🌴", "Palm tree", "nature", ["palm", "tropical", "beach"]),
  E("🍀", "Four leaf clover", "nature", ["clover", "luck", "lucky"]),
  E("🍁", "Maple leaf", "nature", ["maple", "leaf", "autumn"]),
  E("🍂", "Fallen leaf", "nature", ["leaf", "autumn", "fall"]),
  E("🍃", "Leaf fluttering in wind", "nature", ["leaf", "wind", "green"]),
  E("☀️", "Sun", "nature", ["sun", "sunny", "bright"]),
  E("🌤️", "Sun behind small cloud", "nature", ["sun", "partly cloudy", "weather"]),
  E("⛅", "Sun behind cloud", "nature", ["cloudy", "weather", "overcast"]),
  E("🌧️", "Cloud with rain", "nature", ["rain", "weather", "wet"]),
  E("⛈️", "Cloud with lightning and rain", "nature", ["storm", "thunder", "rain"]),
  E("🌨️", "Cloud with snow", "nature", ["snow", "winter", "weather"]),
  E("🌩️", "Cloud with lightning", "nature", ["lightning", "thunder", "storm"]),
  E("🌈", "Rainbow", "nature", ["rainbow", "colorful", "pride"]),
  E("☔", "Umbrella with rain drops", "nature", ["umbrella", "rain", "wet"]),
  E("⚡", "High voltage", "nature", ["lightning", "electricity", "zap"]),
  E("❄️", "Snowflake", "nature", ["snow", "cold", "flake"]),
  E("🔥", "Fire", "nature", ["fire", "hot", "flame", "burn"]),
  E("💧", "Droplet", "nature", ["drop", "water", "droplet"]),
  E("🌊", "Water wave", "nature", ["ocean", "wave", "sea"]),

  // Food & drink
  E("🍎", "Red apple", "food", ["apple", "fruit"]),
  E("🍏", "Green apple", "food", ["apple", "fruit", "green"]),
  E("🍐", "Pear", "food", ["pear", "fruit"]),
  E("🍊", "Tangerine", "food", ["orange", "citrus", "fruit"]),
  E("🍋", "Lemon", "food", ["lemon", "citrus", "sour"]),
  E("🍌", "Banana", "food", ["banana", "fruit"]),
  E("🍉", "Watermelon", "food", ["watermelon", "melon", "fruit"]),
  E("🍇", "Grapes", "food", ["grapes", "fruit", "wine"]),
  E("🍓", "Strawberry", "food", ["strawberry", "berry", "fruit"]),
  E("🫐", "Blueberries", "food", ["blueberry", "berry", "fruit"]),
  E("🍈", "Melon", "food", ["melon", "fruit"]),
  E("🍒", "Cherries", "food", ["cherry", "cherries", "fruit"]),
  E("🍑", "Peach", "food", ["peach", "fruit", "booty"]),
  E("🥭", "Mango", "food", ["mango", "fruit", "tropical"]),
  E("🍍", "Pineapple", "food", ["pineapple", "fruit", "tropical"]),
  E("🥥", "Coconut", "food", ["coconut", "tropical"]),
  E("🥝", "Kiwi fruit", "food", ["kiwi", "fruit"]),
  E("🍅", "Tomato", "food", ["tomato", "vegetable", "fruit"]),
  E("🥑", "Avocado", "food", ["avocado", "guac", "healthy"]),
  E("🥦", "Broccoli", "food", ["broccoli", "vegetable", "healthy"]),
  E("🥬", "Leafy green", "food", ["lettuce", "salad", "green"]),
  E("🥒", "Cucumber", "food", ["cucumber", "pickle"]),
  E("🌽", "Corn", "food", ["corn", "maize", "cob"]),
  E("🥕", "Carrot", "food", ["carrot", "vegetable"]),
  E("🥔", "Potato", "food", ["potato", "vegetable"]),
  E("🍞", "Bread", "food", ["bread", "loaf", "baked"]),
  E("🥐", "Croissant", "food", ["croissant", "pastry", "bakery"]),
  E("🥯", "Bagel", "food", ["bagel", "breakfast", "bread"]),
  E("🥨", "Pretzel", "food", ["pretzel", "snack", "salt"]),
  E("🧀", "Cheese wedge", "food", ["cheese", "dairy", "wedge"]),
  E("🍗", "Poultry leg", "food", ["chicken", "leg", "drumstick"]),
  E("🍔", "Hamburger", "food", ["burger", "hamburger", "fast food"]),
  E("🍟", "French fries", "food", ["fries", "chips", "fast food"]),
  E("🍕", "Pizza", "food", ["pizza", "slice", "cheese"]),
  E("🌭", "Hot dog", "food", ["hot dog", "sausage", "frank"]),
  E("🥪", "Sandwich", "food", ["sandwich", "lunch", "sub"]),
  E("🌮", "Taco", "food", ["taco", "mexican", "food"]),
  E("🌯", "Burrito", "food", ["burrito", "mexican", "wrap"]),
  E("🥗", "Green salad", "food", ["salad", "healthy", "veggies"]),
  E("🍜", "Steaming bowl", "food", ["noodles", "ramen", "soup"]),
  E("🍝", "Spaghetti", "food", ["pasta", "spaghetti", "italian"]),
  E("🍣", "Sushi", "food", ["sushi", "japanese", "fish"]),
  E("🍤", "Fried shrimp", "food", ["shrimp", "tempura", "prawn"]),
  E("🍦", "Soft ice cream", "food", ["ice cream", "soft serve", "dessert"]),
  E("🍨", "Ice cream", "food", ["ice cream", "dessert"]),
  E("🍩", "Doughnut", "food", ["donut", "doughnut", "dessert"]),
  E("🍪", "Cookie", "food", ["cookie", "biscuit", "dessert"]),
  E("🎂", "Birthday cake", "food", ["cake", "birthday", "celebration"]),
  E("🍰", "Shortcake", "food", ["cake", "dessert", "slice"]),
  E("🧁", "Cupcake", "food", ["cupcake", "dessert", "sweet"]),
  E("🍫", "Chocolate bar", "food", ["chocolate", "candy", "sweet"]),
  E("🍬", "Candy", "food", ["candy", "sweet", "sugar"]),
  E("🍭", "Lollipop", "food", ["lollipop", "candy", "sweet"]),
  E("☕", "Hot beverage", "food", ["coffee", "tea", "hot drink"]),
  E("🫖", "Teapot", "food", ["tea", "teapot", "brew"]),
  E("🍵", "Teacup without handle", "food", ["tea", "matcha", "green tea"]),
  E("🧋", "Bubble tea", "food", ["boba", "tapioca", "milk tea"]),
  E("🍶", "Sake", "food", ["sake", "rice wine", "japanese"]),
  E("🍺", "Beer mug", "food", ["beer", "brew", "drink"]),
  E("🍻", "Clinking beer mugs", "food", ["beer", "cheers", "toast"]),
  E("🥂", "Clinking glasses", "food", ["champagne", "cheers", "toast"]),
  E("🍷", "Wine glass", "food", ["wine", "drink", "red"]),
  E("🥤", "Cup with straw", "food", ["soda", "drink", "straw"]),
  E("🧃", "Juice box", "food", ["juice", "box", "drink"]),
  E("🧊", "Ice", "food", ["ice", "ice cube", "cold"]),

  // Activity
  E("⚽", "Soccer ball", "activity", ["football", "soccer", "sport"]),
  E("🏀", "Basketball", "activity", ["basketball", "sport", "hoop"]),
  E("🏈", "American football", "activity", ["football", "nfl", "sport"]),
  E("⚾", "Baseball", "activity", ["baseball", "sport"]),
  E("🎾", "Tennis", "activity", ["tennis", "sport", "racquet"]),
  E("🏐", "Volleyball", "activity", ["volleyball", "sport"]),
  E("🏉", "Rugby football", "activity", ["rugby", "football", "sport"]),
  E("🎱", "Pool 8 ball", "activity", ["billiards", "pool", "8 ball"]),
  E("🏓", "Ping pong", "activity", ["ping pong", "table tennis", "paddle"]),
  E("🏸", "Badminton", "activity", ["badminton", "shuttlecock"]),
  E("🥊", "Boxing glove", "activity", ["boxing", "fight", "glove"]),
  E("🥋", "Martial arts uniform", "activity", ["karate", "judо", "martial arts"]),
  E("🥅", "Goal net", "activity", ["goal", "net", "hockey"]),
  E("⛳", "Flag in hole", "activity", ["golf", "hole", "flag"]),
  E("⛸️", "Ice skate", "activity", ["ice skate", "skating", "winter"]),
  E("🎣", "Fishing pole", "activity", ["fishing", "fish", "rod"]),
  E("🎽", "Running shirt", "activity", ["running", "athlete", "sport"]),
  E("🎿", "Skis", "activity", ["ski", "skiing", "snow"]),
  E("🛷", "Sled", "activity", ["sled", "snow", "winter"]),
  E("🥌", "Curling stone", "activity", ["curling", "stone", "ice"]),
  E("🎯", "Bullseye", "activity", ["target", "darts", "bullseye"]),
  E("🎮", "Video game", "activity", ["gaming", "controller", "play"]),
  E("🎲", "Game die", "activity", ["dice", "game", "board game"]),
  E("🎰", "Slot machine", "activity", ["slots", "casino", "gamble"]),
  E("🧩", "Puzzle piece", "activity", ["puzzle", "jigsaw", "piece"]),
  E("🎨", "Artist palette", "activity", ["art", "palette", "painting"]),
  E("🎭", "Performing arts", "activity", ["theater", "drama", "masks"]),
  E("🎤", "Microphone", "activity", ["mic", "sing", "karaoke"]),
  E("🎧", "Headphone", "activity", ["headphones", "music", "listen"]),
  E("🎼", "Musical score", "activity", ["music", "score", "sheet"]),
  E("🎵", "Musical note", "activity", ["music", "note", "song"]),
  E("🎶", "Musical notes", "activity", ["music", "notes", "song"]),
  E("🎹", "Musical keyboard", "activity", ["piano", "keyboard", "music"]),
  E("🥁", "Drum", "activity", ["drum", "drums", "beat"]),
  E("🎺", "Trumpet", "activity", ["trumpet", "horn", "brass"]),
  E("🎸", "Guitar", "activity", ["guitar", "rock", "strings"]),
  E("🎻", "Violin", "activity", ["violin", "strings", "classical"]),
  E("🎬", "Clapper board", "activity", ["movie", "film", "action"]),
  E("🏆", "Trophy", "activity", ["winner", "award", "champion"]),
  E("🥇", "1st place medal", "activity", ["gold", "first", "winner"]),
  E("🥈", "2nd place medal", "activity", ["silver", "second", "runner up"]),
  E("🥉", "3rd place medal", "activity", ["bronze", "third"]),
  E("🎟️", "Admission tickets", "activity", ["ticket", "event", "admission"]),
  E("🎫", "Ticket", "activity", ["ticket", "event", "entry"]),
  E("🎗️", "Reminder ribbon", "activity", ["ribbon", "awareness", "support"]),
  E("🎖️", "Military medal", "activity", ["medal", "military", "honor"]),
  E("🎪", "Circus tent", "activity", ["circus", "tent", "show"]),
  E("🎠", "Carousel horse", "activity", ["carousel", "merry-go-round", "ride"]),
  E("🎡", "Ferris wheel", "activity", ["ferris wheel", "amusement", "ride"]),
  E("🎢", "Roller coaster", "activity", ["roller coaster", "amusement", "ride"]),

  // Travel & places
  E("🚗", "Automobile", "travel", ["car", "auto", "vehicle"]),
  E("🚕", "Taxi", "travel", ["taxi", "cab", "car"]),
  E("🚙", "Sport utility vehicle", "travel", ["suv", "car", "off-road"]),
  E("🚌", "Bus", "travel", ["bus", "transit", "vehicle"]),
  E("🚎", "Trolleybus", "travel", ["trolley", "bus", "transit"]),
  E("🏎️", "Racing car", "travel", ["race car", "formula", "speed"]),
  E("🚓", "Police car", "travel", ["police", "cop", "car"]),
  E("🚑", "Ambulance", "travel", ["ambulance", "emergency", "medical"]),
  E("🚒", "Fire engine", "travel", ["fire", "firetruck", "engine"]),
  E("🚐", "Minibus", "travel", ["minibus", "van", "shuttle"]),
  E("🚚", "Delivery truck", "travel", ["truck", "delivery", "lorry"]),
  E("🚛", "Articulated lorry", "travel", ["truck", "lorry", "semi"]),
  E("🚜", "Tractor", "travel", ["tractor", "farm", "agriculture"]),
  E("🛵", "Motor scooter", "travel", ["scooter", "moped", "motorcycle"]),
  E("🏍️", "Motorcycle", "travel", ["motorcycle", "bike", "motorbike"]),
  E("🚲", "Bicycle", "travel", ["bike", "bicycle", "cycle"]),
  E("🚄", "High-speed train", "travel", ["train", "bullet", "shinkansen"]),
  E("🚅", "Bullet train", "travel", ["train", "bullet", "shinkansen"]),
  E("🚆", "Train", "travel", ["train", "rail", "subway"]),
  E("🚇", "Metro", "travel", ["metro", "subway", "underground"]),
  E("🚈", "Light rail", "travel", ["light rail", "train", "transit"]),
  E("🚉", "Station", "travel", ["station", "train", "platform"]),
  E("✈️", "Airplane", "travel", ["plane", "flight", "air"]),
  E("🚀", "Rocket", "travel", ["space", "launch", "ship", "blast off"]),
  E("🛸", "Flying saucer", "travel", ["ufo", "alien", "saucer"]),
  E("🚁", "Helicopter", "travel", ["helicopter", "chopper", "air"]),
  E("🛶", "Canoe", "travel", ["canoe", "paddle", "boat"]),
  E("⛵", "Sailboat", "travel", ["sailboat", "boat", "sail"]),
  E("🚤", "Speedboat", "travel", ["speedboat", "boat", "motorboat"]),
  E("🛳️", "Passenger ship", "travel", ["cruise", "ship", "ferry"]),
  E("🗺️", "World map", "travel", ["map", "world", "navigation"]),
  E("🗽", "Statue of Liberty", "travel", ["statue", "liberty", "new york"]),
  E("🗼", "Tokyo tower", "travel", ["tokyo", "tower", "japan"]),
  E("🏰", "Castle", "travel", ["castle", "fairy tale", "fortress"]),
  E("🏯", "Japanese castle", "travel", ["castle", "japan", "shogun"]),
  E("🏟️", "Stadium", "travel", ["stadium", "arena", "sports"]),
  E("🎡", "Ferris wheel", "travel", ["ferris wheel", "amusement", "ride"]),
  E("🏖️", "Beach with umbrella", "travel", ["beach", "vacation", "umbrella"]),
  E("🏝️", "Desert island", "travel", ["island", "desert", "tropical"]),
  E("🏜️", "Desert", "travel", ["desert", "sand", "dune"]),
  E("🌋", "Volcano", "travel", ["volcano", "lava", "eruption"]),
  E("⛰️", "Mountain", "travel", ["mountain", "peak", "hike"]),
  E("🏔️", "Snow-capped mountain", "travel", ["mountain", "snow", "peak"]),
  E("🏠", "House", "travel", ["house", "home", "building"]),
  E("🏡", "House with garden", "travel", ["home", "garden", "house"]),
  E("🏢", "Office building", "travel", ["office", "building", "work"]),
  E("🏬", "Department store", "travel", ["store", "mall", "shopping"]),
  E("🏨", "Hotel", "travel", ["hotel", "lodging", "stay"]),
  E("🏪", "Convenience store", "travel", ["convenience", "store", "7 eleven"]),
  E("🏫", "School", "travel", ["school", "education", "classroom"]),
  E("⛪", "Church", "travel", ["church", "worship", "cathedral"]),
  E("🕌", "Mosque", "travel", ["mosque", "worship", "islam"]),
  E("🛕", "Hindu temple", "travel", ["temple", "hindu", "worship"]),
  E("💒", "Wedding", "travel", ["wedding", "church", "marriage"]),
  E("🏥", "Hospital", "travel", ["hospital", "medical", "clinic"]),
  E("🏦", "Bank", "travel", ["bank", "money", "finance"]),
  E("🏛️", "Classical building", "travel", ["building", "classical", "government"]),
  E("⛲", "Fountain", "travel", ["fountain", "water", "park"]),
  E("🏕️", "Camping", "travel", ["camp", "camping", "tent"]),
  E("🌄", "Sunrise over mountains", "travel", ["sunrise", "morning", "mountains"]),
  E("🌅", "Sunrise", "travel", ["sunrise", "dawn", "morning"]),
  E("🌇", "Sunset", "travel", ["sunset", "evening", "city"]),
  E("🌆", "Cityscape at dusk", "travel", ["city", "dusk", "skyline"]),
  E("🌃", "Night with stars", "travel", ["night", "stars", "city"]),
  E("🌉", "Bridge at night", "travel", ["bridge", "night", "water"]),
  E("🎑", "Moon viewing ceremony", "travel", ["moon", "tsukimi", "japan"]),
  E("🌌", "Milky Way", "travel", ["milky way", "galaxy", "stars"]),

  // Objects
  E("⌚", "Watch", "objects", ["watch", "time", "wrist"]),
  E("📱", "Mobile phone", "objects", ["phone", "smartphone", "mobile"]),
  E("💻", "Laptop", "objects", ["computer", "laptop", "mac"]),
  E("🖥️", "Desktop computer", "objects", ["computer", "desktop", "monitor"]),
  E("🖨️", "Printer", "objects", ["printer", "print", "office"]),
  E("⌨️", "Keyboard", "objects", ["keyboard", "type", "input"]),
  E("🖱️", "Computer mouse", "objects", ["mouse", "pointer", "computer"]),
  E("💽", "Computer disk", "objects", ["disk", "cd", "computer"]),
  E("💾", "Floppy disk", "objects", ["floppy", "save", "disk"]),
  E("💿", "Optical disk", "objects", ["cd", "disc", "disk"]),
  E("📀", "DVD", "objects", ["dvd", "disc", "disk"]),
  E("📷", "Camera", "objects", ["camera", "photo", "picture"]),
  E("📸", "Camera with flash", "objects", ["camera", "photo", "flash"]),
  E("📹", "Video camera", "objects", ["video", "camera", "record"]),
  E("🎥", "Movie camera", "objects", ["movie", "film", "camera"]),
  E("📺", "Television", "objects", ["tv", "television", "watch"]),
  E("📻", "Radio", "objects", ["radio", "listen", "music"]),
  E("🎙️", "Studio microphone", "objects", ["mic", "studio", "podcast"]),
  E("🎚️", "Level slider", "objects", ["slider", "level", "mixer"]),
  E("🎛️", "Control knobs", "objects", ["knobs", "control", "mixer"]),
  E("⏰", "Alarm clock", "objects", ["alarm", "clock", "wake"]),
  E("⏲️", "Timer clock", "objects", ["timer", "clock", "countdown"]),
  E("🕰️", "Mantelpiece clock", "objects", ["clock", "mantel", "antique"]),
  E("🕛", "Twelve o'clock", "objects", ["clock", "time", "twelve"]),
  E("🕒", "Three o'clock", "objects", ["clock", "time", "three"]),
  E("🕕", "Six o'clock", "objects", ["clock", "time", "six"]),
  E("🕘", "Nine o'clock", "objects", ["clock", "time", "nine"]),
  E("🧭", "Compass", "objects", ["compass", "navigation", "direction"]),
  E("🔋", "Battery", "objects", ["battery", "power", "charge"]),
  E("🔌", "Electric plug", "objects", ["plug", "electric", "power"]),
  E("💡", "Light bulb", "objects", ["bulb", "idea", "light"]),
  E("🔦", "Flashlight", "objects", ["flashlight", "torch", "light"]),
  E("🕯️", "Candle", "objects", ["candle", "light", "wax"]),
  E("🧯", "Fire extinguisher", "objects", ["fire", "extinguisher", "safety"]),
  E("🔍", "Magnifying glass tilted left", "objects", ["search", "zoom", "magnify"]),
  E("🔎", "Magnifying glass tilted right", "objects", ["search", "zoom", "magnify"]),
  E("🔧", "Wrench", "objects", ["wrench", "tool", "fix"]),
  E("🔨", "Hammer", "objects", ["hammer", "tool", "fix"]),
  E("🪛", "Screwdriver", "objects", ["screwdriver", "tool", "fix"]),
  E("⚙️", "Gear", "objects", ["gear", "settings", "mechanics"]),
  E("🗜️", "Clamp", "objects", ["clamp", "tool", "vise"]),
  E("⚖️", "Balance scale", "objects", ["balance", "justice", "scale"]),
  E("🔗", "Link", "objects", ["link", "chain", "hyperlink"]),
  E("🧰", "Toolbox", "objects", ["tools", "toolbox", "fix"]),
  E("🔬", "Microscope", "objects", ["microscope", "science", "lab"]),
  E("🔭", "Telescope", "objects", ["telescope", "space", "observe"]),
  E("📐", "Triangular ruler", "objects", ["ruler", "triangle", "geometry"]),
  E("📏", "Straight ruler", "objects", ["ruler", "measure", "length"]),
  E("🧮", "Abacus", "objects", ["abacus", "math", "count"]),
  E("📔", "Notebook with decorative cover", "objects", ["notebook", "journal", "book"]),
  E("📕", "Closed book", "objects", ["book", "closed", "read"]),
  E("📖", "Open book", "objects", ["book", "open", "read"]),
  E("📗", "Green book", "objects", ["book", "green"]),
  E("📘", "Blue book", "objects", ["book", "blue"]),
  E("📙", "Orange book", "objects", ["book", "orange"]),
  E("📚", "Books", "objects", ["books", "library", "stack"]),
  E("📓", "Notebook", "objects", ["notebook", "journal"]),
  E("📒", "Ledger", "objects", ["ledger", "notebook", "accounting"]),
  E("📃", "Page with curl", "objects", ["page", "curl", "document"]),
  E("📜", "Scroll", "objects", ["scroll", "ancient", "document"]),
  E("📄", "Page facing up", "objects", ["page", "document", "paper"]),
  E("📰", "Newspaper", "objects", ["newspaper", "news", "paper"]),
  E("📑", "Bookmark tabs", "objects", ["bookmark", "tabs", "labels"]),
  E("🔖", "Bookmark", "objects", ["bookmark", "mark", "save"]),
  E("💰", "Money bag", "objects", ["money", "cash", "wealth"]),
  E("💳", "Credit card", "objects", ["card", "credit", "payment"]),
  E("💵", "Dollar banknote", "objects", ["dollar", "money", "cash"]),
  E("💴", "Yen banknote", "objects", ["yen", "money", "japan"]),
  E("💶", "Euro banknote", "objects", ["euro", "money", "europe"]),
  E("💷", "Pound banknote", "objects", ["pound", "money", "uk"]),
  E("🪙", "Coin", "objects", ["coin", "money", "change"]),
  E("✉️", "Envelope", "objects", ["mail", "email", "envelope"]),
  E("📧", "E-mail", "objects", ["email", "mail", "message"]),
  E("📨", "Incoming envelope", "objects", ["mail", "incoming", "envelope"]),
  E("📩", "Envelope with arrow", "objects", ["mail", "outgoing", "envelope"]),
  E("📤", "Outbox tray", "objects", ["outbox", "send", "mail"]),
  E("📥", "Inbox tray", "objects", ["inbox", "receive", "mail"]),
  E("📦", "Package", "objects", ["package", "box", "parcel"]),
  E("📫", "Closed mailbox with raised flag", "objects", ["mailbox", "mail", "post"]),
  E("📬", "Open mailbox with raised flag", "objects", ["mailbox", "mail", "post"]),
  E("📭", "Open mailbox with lowered flag", "objects", ["mailbox", "mail", "post"]),
  E("📮", "Postbox", "objects", ["postbox", "mail", "post"]),
  E("✏️", "Pencil", "objects", ["pencil", "write", "draw"]),
  E("✒️", "Black nib", "objects", ["pen", "nib", "write"]),
  E("🖊️", "Pen", "objects", ["pen", "write", "ink"]),
  E("🖌️", "Paintbrush", "objects", ["paintbrush", "paint", "brush"]),
  E("🖍️", "Crayon", "objects", ["crayon", "color", "draw"]),
  E("📝", "Memo", "objects", ["memo", "note", "write"]),
  E("📌", "Pushpin", "objects", ["pushpin", "pin", "map"]),
  E("📍", "Round pushpin", "objects", ["pin", "location", "map"]),
  E("📎", "Paperclip", "objects", ["paperclip", "attach", "clip"]),
  E("🗂️", "Card index dividers", "objects", ["dividers", "organize", "files"]),
  E("📁", "File folder", "objects", ["folder", "file", "directory"]),
  E("📂", "Open file folder", "objects", ["folder", "open", "directory"]),
  E("🗓️", "Calendar", "objects", ["calendar", "date", "schedule"]),
  E("📅", "Calendar", "objects", ["calendar", "date", "schedule"]),
  E("📆", "Tear-off calendar", "objects", ["calendar", "date", "schedule"]),
  E("🗒️", "Spiral notepad", "objects", ["notepad", "note", "spiral"]),
  E("📇", "Card index", "objects", ["card", "index", "contacts"]),
  E("🗃️", "Card file box", "objects", ["card", "file", "box"]),
  E("🗄️", "File cabinet", "objects", ["cabinet", "file", "filing"]),
  E("🗑️", "Wastebasket", "objects", ["trash", "bin", "delete"]),
  E("🔒", "Locked", "objects", ["lock", "locked", "secure"]),
  E("🔓", "Unlocked", "objects", ["unlock", "open", "lock"]),
  E("🔏", "Locked with pen", "objects", ["lock", "signed", "secure"]),
  E("🔐", "Locked with key", "objects", ["lock", "secure", "key"]),
  E("🔑", "Key", "objects", ["key", "unlock", "password"]),
  E("🗝️", "Old key", "objects", ["key", "old", "antique"]),
  E("🪓", "Axe", "objects", ["axe", "cut", "tool"]),
  E("🔪", "Kitchen knife", "objects", ["knife", "cut", "cook"]),
  E("🛡️", "Shield", "objects", ["shield", "protect", "guard"]),
  E("🔫", "Pistol", "objects", ["gun", "water gun", "toy"]),
  E("💣", "Bomb", "objects", ["bomb", "explosive", "explode"]),
  E("🧨", "Firecracker", "objects", ["firecracker", "explosion", "celebration"]),
  E("🛎️", "Bellhop bell", "objects", ["bell", "service", "hotel"]),
  E("🧸", "Teddy bear", "objects", ["teddy", "bear", "toy"]),
  E("🖼️", "Framed picture", "objects", ["picture", "frame", "art"]),
  E("🎁", "Wrapped gift", "objects", ["gift", "present", "birthday"]),
  E("🎊", "Confetti ball", "objects", ["confetti", "celebration", "party"]),
  E("🎈", "Balloon", "objects", ["balloon", "party", "celebration"]),
  E("🎏", "Carp streamer", "objects", ["carp", "streamer", "japan"]),
  E("🎀", "Ribbon", "objects", ["ribbon", "bow", "gift"]),
  E("🎫", "Ticket", "objects", ["ticket", "event", "entry"]),
  E("🏷️", "Label", "objects", ["label", "tag", "price"]),
  E("🧾", "Receipt", "objects", ["receipt", "bill", "invoice"]),
  E("🔴", "Red circle", "symbols", ["circle", "red", "dot"]),
  E("🟠", "Orange circle", "symbols", ["circle", "orange", "dot"]),
  E("🟡", "Yellow circle", "symbols", ["circle", "yellow", "dot"]),
  E("🟢", "Green circle", "symbols", ["circle", "green", "dot"]),
  E("🔵", "Blue circle", "symbols", ["circle", "blue", "dot"]),
  E("🟣", "Purple circle", "symbols", ["circle", "purple", "dot"]),
  E("⚫", "Black circle", "symbols", ["circle", "black", "dot"]),
  E("⚪", "White circle", "symbols", ["circle", "white", "dot"]),

  // Symbols
  E("❤️", "Red heart", "symbols", ["love", "heart", "red"]),
  E("💯", "Hundred points", "symbols", ["100", "perfect", "score"]),
  E("💢", "Anger symbol", "symbols", ["angry", "mad", "vein"]),
  E("💥", "Collision", "symbols", ["boom", "explosion", "impact"]),
  E("💫", "Dizzy", "symbols", ["dizzy", "sparkle", "star"]),
  E("💦", "Sweat droplets", "symbols", ["sweat", "water", "drops"]),
  E("💨", "Dashing away", "symbols", ["wind", "speed", "dash"]),
  E("💬", "Speech balloon", "symbols", ["chat", "speech", "bubble", "talk"]),
  E("💭", "Thought balloon", "symbols", ["thought", "think", "bubble"]),
  E("💤", "Zzz", "symbols", ["sleep", "tired", "zzz"]),
  E("☮️", "Peace symbol", "symbols", ["peace", "hippie"]),
  E("✝️", "Latin cross", "symbols", ["cross", "christian", "religion"]),
  E("☪️", "Star and crescent", "symbols", ["islam", "moon", "star"]),
  E("☸️", "Wheel of dharma", "symbols", ["buddhism", "dharma", "wheel"]),
  E("✡️", "Star of David", "symbols", ["judaism", "david", "star"]),
  E("🔯", "Six pointed star", "symbols", ["star", "six", "occult"]),
  E("🕉️", "Om", "symbols", ["om", "hindu", "spiritual"]),
  E("☯️", "Yin yang", "symbols", ["yin", "yang", "balance"]),
  E("♈", "Aries", "symbols", ["zodiac", "aries", "horoscope"]),
  E("♉", "Taurus", "symbols", ["zodiac", "taurus", "horoscope"]),
  E("♊", "Gemini", "symbols", ["zodiac", "gemini", "horoscope"]),
  E("♋", "Cancer", "symbols", ["zodiac", "cancer", "horoscope"]),
  E("♌", "Leo", "symbols", ["zodiac", "leo", "horoscope"]),
  E("♍", "Virgo", "symbols", ["zodiac", "virgo", "horoscope"]),
  E("♎", "Libra", "symbols", ["zodiac", "libra", "horoscope"]),
  E("♏", "Scorpio", "symbols", ["zodiac", "scorpio", "horoscope"]),
  E("♐", "Sagittarius", "symbols", ["zodiac", "sagittarius", "horoscope"]),
  E("♑", "Capricorn", "symbols", ["zodiac", "capricorn", "horoscope"]),
  E("♒", "Aquarius", "symbols", ["zodiac", "aquarius", "horoscope"]),
  E("♓", "Pisces", "symbols", ["zodiac", "pisces", "horoscope"]),
  E("🆕", "NEW button", "symbols", ["new", "fresh", "button"]),
  E("🆙", "UP! button", "symbols", ["up", "upgrade", "button"]),
  E("🆒", "COOL button", "symbols", ["cool", "fresh", "button"]),
  E("🆓", "FREE button", "symbols", ["free", "gratis", "button"]),
  E("🆖", "NG button", "symbols", ["ng", "no good", "button"]),
  E("🆗", "OK button", "symbols", ["ok", "yes", "button"]),
  E("🆘", "SOS button", "symbols", ["sos", "help", "emergency"]),
  E("🆚", "VS button", "symbols", ["vs", "versus", "fight"]),
  E("🈁", "Japanese here button", "symbols", ["here", "japanese", "button"]),
  E("🈚", "Japanese free button", "symbols", ["free", "japanese", "button"]),
  E("🈸", "Japanese application button", "symbols", ["application", "japanese", "button"]),
  E("🈳", "Japanese vacancy button", "symbols", ["vacancy", "japanese", "button"]),
  E("🈴", "Japanese passing grade button", "symbols", ["passing", "japanese", "grade"]),
  E("🈲", "Japanese prohibited button", "symbols", ["prohibited", "forbidden", "japanese"]),
  E("🈶", "Japanese not free button", "symbols", ["not free", "fee", "japanese"]),
  E("🈺", "Japanese open for business button", "symbols", ["open", "business", "japanese"]),
  E("🈷️", "Japanese monthly amount button", "symbols", ["monthly", "amount", "japanese"]),
  E("🈵", "Japanese full button", "symbols", ["full", "japanese", "button"]),
  E("〽️", "Part alternation mark", "symbols", ["part", "alternation", "mark"]),
  E("⚠️", "Warning", "symbols", ["warning", "caution", "alert"]),
  E("🚸", "Children crossing", "symbols", ["children", "crossing", "school"]),
  E("⛔", "No entry", "symbols", ["no entry", "prohibited", "stop"]),
  E("🚫", "Prohibited", "symbols", ["no", "prohibited", "forbidden"]),
  E("🚳", "No bicycles", "symbols", ["no bikes", "prohibited", "bicycle"]),
  E("🚭", "No smoking", "symbols", ["no smoking", "prohibited", "smoke"]),
  E("🚯", "No littering", "symbols", ["no litter", "prohibited", "trash"]),
  E("🚱", "Non-potable water", "symbols", ["water", "non-potable", "drink"]),
  E("🚷", "No pedestrians", "symbols", ["no walking", "prohibited", "pedestrian"]),
  E("📵", "No mobile phones", "symbols", ["no phones", "prohibited", "phone"]),
  E("🔞", "No one under eighteen", "symbols", ["18", "18+", "adult"]),
  E("🔃", "Clockwise vertical arrows", "symbols", ["clockwise", "refresh", "arrows"]),
  E("🔄", "Counterclockwise arrows", "symbols", ["refresh", "counterclockwise", "arrows"]),
  E("🔙", "BACK arrow", "symbols", ["back", "arrow", "return"]),
  E("🔚", "END arrow", "symbols", ["end", "arrow", "finish"]),
  E("🔛", "ON! arrow", "symbols", ["on", "arrow", "start"]),
  E("🔜", "SOON arrow", "symbols", ["soon", "arrow", "coming"]),
  E("🔝", "TOP arrow", "symbols", ["top", "arrow", "up"]),
  E("✅", "Check mark button", "symbols", ["check", "yes", "done"]),
  E("☑️", "Check box with check", "symbols", ["check", "box", "tick"]),
  E("✔️", "Check mark", "symbols", ["check", "tick", "correct"]),
  E("❌", "Cross mark", "symbols", ["x", "cross", "wrong"]),
  E("❎", "Cross mark button", "symbols", ["x", "cross", "no"]),
  E("➕", "Plus", "symbols", ["plus", "add", "more"]),
  E("➖", "Minus", "symbols", ["minus", "subtract", "less"]),
  E("➗", "Divide", "symbols", ["divide", "division", "math"]),
  E("✖️", "Multiply", "symbols", ["multiply", "times", "math"]),
  E("❓", "Red question mark", "symbols", ["question", "help", "?"]),
  E("❔", "White question mark", "symbols", ["question", "help", "?"]),
  E("❕", "White exclamation mark", "symbols", ["exclamation", "!", "alert"]),
  E("❗", "Red exclamation mark", "symbols", ["exclamation", "!", "alert"]),
  E("💲", "Heavy dollar sign", "symbols", ["dollar", "money", "currency"]),
  E("🔟", "Keycap ten", "symbols", ["10", "ten", "number"]),
  E("🔁", "Repeat button", "symbols", ["repeat", "loop", "play"]),
  E("🔂", "Repeat single button", "symbols", ["repeat", "loop", "one"]),
  E("🔀", "Shuffle tracks button", "symbols", ["shuffle", "random", "tracks"]),
  E("▶️", "Play button", "symbols", ["play", "start", "video"]),
  E("⏸️", "Pause button", "symbols", ["pause", "stop", "video"]),
  E("⏹️", "Stop button", "symbols", ["stop", "halt", "video"]),
  E("⏺️", "Record button", "symbols", ["record", "video", "dot"]),
  E("⏭️", "Next track button", "symbols", ["next", "skip", "track"]),
  E("⏮️", "Previous track button", "symbols", ["previous", "skip", "track"]),
  E("⏩", "Fast-forward button", "symbols", ["fast forward", "speed", "video"]),
  E("⏪", "Fast reverse button", "symbols", ["rewind", "back", "video"]),
  E("⏫", "Fast up button", "symbols", ["up", "fast", "double"]),
  E("⏬", "Fast down button", "symbols", ["down", "fast", "double"]),
  E("⏯️", "Play or pause button", "symbols", ["play", "pause", "video"]),
  E("🔆", "Bright button", "symbols", ["bright", "brightness", "light"]),
  E("🔅", "Dim button", "symbols", ["dim", "low", "light"]),
  E("🔱", "Trident emblem", "symbols", ["trident", "emblem", "poseidon"]),
  E("📛", "Name badge", "symbols", ["name", "badge", "id"]),
  E("🎵", "Musical note", "symbols", ["music", "note", "song"]),
  E("🎶", "Musical notes", "symbols", ["music", "notes", "song"]),
  E("🔔", "Bell", "symbols", ["bell", "notification", "ring"]),
  E("🔕", "Bell with slash", "symbols", ["bell", "muted", "silent"]),
  E("♻️", "Recycling symbol", "symbols", ["recycle", "recycling", "green"]),
  E("🛗", "Elevator", "symbols", ["elevator", "lift", "up"]),
  E("🏧", "ATM sign", "symbols", ["atm", "cash", "money"]),
  E("🚮", "Litter in bin sign", "symbols", ["litter", "bin", "trash"]),
  E("🚰", "Potable water", "symbols", ["water", "drink", "potable"]),
  E("♿", "Wheelchair symbol", "symbols", ["wheelchair", "accessibility", "disabled"]),
  E("🚹", "Men's room", "symbols", ["men", "restroom", "male"]),
  E("🚺", "Women's room", "symbols", ["women", "restroom", "female"]),
  E("🚼", "Baby symbol", "symbols", ["baby", "nursery", "changing"]),
  E("🚻", "Restroom", "symbols", ["restroom", "toilet", "bathroom"]),
  E("🚾", "Water closet", "symbols", ["wc", "toilet", "restroom"]),
  E("Ⓜ️", "Circled M", "symbols", ["m", "circled", "metro"]),
  E("🅰️", "A button", "symbols", ["a", "letter", "blood type"]),
  E("🅱️", "B button", "symbols", ["b", "letter", "blood type"]),
  E("🅾️", "O button", "symbols", ["o", "letter", "blood type"]),
  E("🅿️", "P button", "symbols", ["parking", "p", "car"]),
  E("🛂", "Passport control", "symbols", ["passport", "control", "border"]),
  E("🛃", "Customs", "symbols", ["customs", "border", "duty"]),
  E("🛄", "Baggage claim", "symbols", ["baggage", "luggage", "claim"]),
  E("🛅", "Left luggage", "symbols", ["luggage", "locker", "left"]),
  E("🎦", "Cinema", "symbols", ["cinema", "movie", "theater"]),
  E("📶", "Antenna bars", "symbols", ["signal", "bars", "network"]),
  E("📳", "Vibration mode", "symbols", ["vibrate", "phone", "mode"]),
  E("📴", "Mobile phone off", "symbols", ["phone off", "power", "off"]),
  E("➡️", "Right arrow", "symbols", ["right", "arrow", "next"]),
  E("⬅️", "Left arrow", "symbols", ["left", "arrow", "back"]),
  E("⬆️", "Up arrow", "symbols", ["up", "arrow", "above"]),
  E("⬇️", "Down arrow", "symbols", ["down", "arrow", "below"]),
  E("↗️", "Up-right arrow", "symbols", ["up right", "arrow", "diagonal"]),
  E("↘️", "Down-right arrow", "symbols", ["down right", "arrow", "diagonal"]),
  E("↙️", "Down-left arrow", "symbols", ["down left", "arrow", "diagonal"]),
  E("↖️", "Up-left arrow", "symbols", ["up left", "arrow", "diagonal"]),
  E("↔️", "Left-right arrow", "symbols", ["left right", "arrow", "horizontal"]),
  E("↕️", "Up-down arrow", "symbols", ["up down", "arrow", "vertical"]),
  E("↪️", "Left arrow curving right", "symbols", ["return", "arrow", "right"]),
  E("↩️", "Right arrow curving left", "symbols", ["return", "arrow", "left"]),
  E("⤴️", "Right arrow curving up", "symbols", ["arrow", "up", "turn"]),
  E("⤵️", "Right arrow curving down", "symbols", ["arrow", "down", "turn"]),
  E("#️⃣", "Hash", "symbols", ["hash", "number", "hashtag"]),
  E("*️⃣", "Asterisk", "symbols", ["asterisk", "star", "star key"]),
  E("0️⃣", "Keycap 0", "symbols", ["0", "zero", "number"]),
  E("1️⃣", "Keycap 1", "symbols", ["1", "one", "number"]),
  E("2️⃣", "Keycap 2", "symbols", ["2", "two", "number"]),
  E("3️⃣", "Keycap 3", "symbols", ["3", "three", "number"]),
  E("4️⃣", "Keycap 4", "symbols", ["4", "four", "number"]),
  E("5️⃣", "Keycap 5", "symbols", ["5", "five", "number"]),
  E("6️⃣", "Keycap 6", "symbols", ["6", "six", "number"]),
  E("7️⃣", "Keycap 7", "symbols", ["7", "seven", "number"]),
  E("8️⃣", "Keycap 8", "symbols", ["8", "eight", "number"]),
  E("9️⃣", "Keycap 9", "symbols", ["9", "nine", "number"]),

  // Flags
  E("🏁", "Chequered flag", "flags", ["checkered", "racing", "finish"]),
  E("🚩", "Triangular flag", "flags", ["flag", "triangular", "marker"]),
  E("🎌", "Crossed flags", "flags", ["crossed", "flags", "japan"]),
  E("🏴", "Black flag", "flags", ["black", "flag", "pirate"]),
  E("🏳️", "White flag", "flags", ["white", "flag", "surrender"]),
  E("🏳️‍🌈", "Rainbow flag", "flags", ["rainbow", "pride", "lgbtq"]),
  E("🏴‍☠️", "Pirate flag", "flags", ["pirate", "skull", "flag"]),
  E("🇺🇸", "United States", "flags", ["usa", "america", "us"]),
  E("🇬🇧", "United Kingdom", "flags", ["uk", "britain", "england"]),
  E("🇨🇦", "Canada", "flags", ["canada", "canadian"]),
  E("🇦🇺", "Australia", "flags", ["australia", "aussie"]),
  E("🇳🇿", "New Zealand", "flags", ["new zealand", "kiwi"]),
  E("🇮🇳", "India", "flags", ["india", "indian"]),
  E("🇨🇳", "China", "flags", ["china", "chinese"]),
  E("🇯🇵", "Japan", "flags", ["japan", "japanese"]),
  E("🇰🇷", "South Korea", "flags", ["korea", "south korea", "korean"]),
  E("🇸🇬", "Singapore", "flags", ["singapore", "sg"]),
  E("🇲🇾", "Malaysia", "flags", ["malaysia", "my"]),
  E("🇮🇩", "Indonesia", "flags", ["indonesia", "id"]),
  E("🇵🇭", "Philippines", "flags", ["philippines", "ph"]),
  E("🇹🇭", "Thailand", "flags", ["thailand", "thai"]),
  E("🇻🇳", "Vietnam", "flags", ["vietnam", "vietnamese"]),
  E("🇦🇪", "United Arab Emirates", "flags", ["uae", "emirates", "dubai"]),
  E("🇸🇦", "Saudi Arabia", "flags", ["saudi", "arabia", "ksa"]),
  E("🇧🇷", "Brazil", "flags", ["brazil", "brazilian"]),
  E("🇲🇽", "Mexico", "flags", ["mexico", "mexican"]),
  E("🇫🇷", "France", "flags", ["france", "french"]),
  E("🇩🇪", "Germany", "flags", ["germany", "german"]),
  E("🇮🇹", "Italy", "flags", ["italy", "italian"]),
  E("🇪🇸", "Spain", "flags", ["spain", "spanish"]),
  E("🇵🇹", "Portugal", "flags", ["portugal", "portuguese"]),
  E("🇳🇱", "Netherlands", "flags", ["netherlands", "dutch", "holland"]),
  E("🇧🇪", "Belgium", "flags", ["belgium", "belgian"]),
  E("🇨🇭", "Switzerland", "flags", ["switzerland", "swiss"]),
  E("🇸🇪", "Sweden", "flags", ["sweden", "swedish"]),
  E("🇳🇴", "Norway", "flags", ["norway", "norwegian"]),
  E("🇩🇰", "Denmark", "flags", ["denmark", "danish"]),
  E("🇫🇮", "Finland", "flags", ["finland", "finnish"]),
  E("🇮🇪", "Ireland", "flags", ["ireland", "irish"]),
  E("🇪🇺", "European Union", "flags", ["eu", "europe", "union"]),
  E("🇷🇺", "Russia", "flags", ["russia", "russian"]),
  E("🇹🇷", "Turkey", "flags", ["turkey", "turkish"]),
  E("🇬🇷", "Greece", "flags", ["greece", "greek"]),
  E("🇪🇬", "Egypt", "flags", ["egypt", "egyptian"]),
  E("🇳🇬", "Nigeria", "flags", ["nigeria", "nigerian"]),
  E("🇰🇪", "Kenya", "flags", ["kenya", "kenyan"]),
  E("🇿🇦", "South Africa", "flags", ["south africa", "rsa"]),
];

/** Flat search index — name + keywords, precomputed once at module load. */
export const EMOJI_INDEX: { e: EmojiEntry; haystack: string }[] = EMOJIS.map((e) => ({
  e,
  haystack: `${e.name} ${e.keywords.join(" ")}`.toLowerCase(),
}));

/** Categories in display order, each with its emoji list. */
export const EMOJI_BY_CATEGORY = EMOJI_CATEGORIES.map((c) => ({
  ...c,
  emojis: EMOJIS.filter((e) => e.category === c.key),
})).filter((c) => c.emojis.length > 0);

/** Search the flat index. Name matches sort before keyword-only matches. */
export function searchEmojis(query: string): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const name: EmojiEntry[] = [];
  const kw: EmojiEntry[] = [];
  for (const { e, haystack } of EMOJI_INDEX) {
    if (e.name.toLowerCase().includes(q)) name.push(e);
    else if (haystack.includes(q)) kw.push(e);
  }
  return [...name, ...kw].slice(0, 120);
}

/** Apply a Fitzpatrick skin-tone modifier when the emoji supports it. */
export function applySkinTone(e: EmojiEntry, tone: string): string {
  return e.skinTones && tone ? e.char + tone : e.char;
}
